# Welcome to the Practice Exercise on Tensorflow Basics. 
<i> It is strongly recommended that you run the notebook on google colab.
We will start with installing the newly launched tensorflow 2.0 and we will check the version post installation to verify the install is successful.

In [65]:
!pip install tensorflow==2.0.0

  Using cached https://files.pythonhosted.org/packages/46/0f/7bd55361168bb32796b360ad15a25de6966c9c1beb58a8e30c01c8279862/tensorflow-2.0.0-cp36-cp36m-manylinux2010_x86_64.whl
  Using cached https://files.pythonhosted.org/packages/fc/08/8b927337b7019c374719145d1dceba21a8bb909b93b1ad6f8fb7d22c1ca1/tensorflow_estimator-2.0.1-py2.py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/76/54/99b9d5d52d5cb732f099baaaf7740403e83fe6b0cedde940fabd2b13d75a/tensorboard-2.0.2-py3-none-any.whl
ERROR: tensorflow-federated 0.12.0 has requirement tensorflow~=2.1.0, but you'll have tensorflow 2.0.0 which is incompatible.
ERROR: tensorflow-federated 0.12.0 has requirement tensorflow-addons~=0.7.0, but you'll have tensorflow-addons 0.8.3 which is incompatible.
  Found existing installation: tensorflow-estimator 2.1.0
    Uninstalling tensorflow-estimator-2.1.0:
      Successfully uninstalled tensorflow-estimator-2.1.0
  Found existing installation: tensorboard 2.1.1
    Uninstalling tenso

#### Let us verify the version we are using. Run the cell below to check the version.

In [67]:
import tensorflow as tf
print(tf.__version__)

2.0.0


# TensorFlow Fundamentals
As per the TensorFlow website, TensorFlow is "an end-to-end open source platform for machine learning. It has a comprehensive, flexible ecosystem of tools, libraries and community resources that lets researchers push the state-of-the-art in ML and developers easily build and deploy ML powered applications."

Learning to work with tensorflow comes handy in developing ML and DL models and in this notebooks we will quickly have a look at the fundamentals/basics of tensorflow. Note that a very detailed understanding of TensorFlow are not required for this course and we will cover some very basic concepts here. You can go ahead and explore this [site](https://www.tensorflow.org/) if you are further interested.

<i>Note that the notebook is for practice and expects some amount of research from the learners.
<br>You are advised to try the code once yourself and then refer to the complete notebook.

### Basic operations with TensorFlow

In [68]:
a = 4 + 2j #complex number
b = 6 + 7j

c = a + b
d = tf.square(c)
print(a,b,c,d)



print(a-b)
print(a*b)

(4+2j) (6+7j) (10+9j) tf.Tensor((19+180j), shape=(), dtype=complex128)
(-2-5j)
(10+40j)


### Tensors
As we Know, tensors are array of numbers arranged in space. We can call a vector(1-D array) as a 1st order tensor and matrix(2-D Array) as a 2nd order tensor and so on. Below, find out how to create a [constant](https://www.tensorflow.org/api_docs/python/tf/constant) tensor:






In [69]:
c = tf.constant([[1.4, 2.0, 2], [8, 2, 5]])
print(c)

tf.Tensor(
[[1.4 2.  2. ]
 [8.  2.  5. ]], shape=(2, 3), dtype=float32)


You can get its value as a Numpy array by calling `.numpy()`:

In [70]:
import numpy as np
y = np.array([[1, 2, 2], [8, 2, 5]])
print(y)
# We can also convert a tensor into a numpy array by using .numpy()
c.numpy()

[[1 2 2]
 [8 2 5]]


array([[1.4, 2. , 2. ],
       [8. , 2. , 5. ]], dtype=float32)

We can get the dimensions and the datatype of the a tf.tensor as demonstrated below - 

In [71]:
print('Tensor Data Type', c.dtype)
print('Tensor Shape', c.shape)
# You can notice the similarity with numpy 
# You can also call the different default tensors as you would do for numpy

Tensor Data Type <dtype: 'float32'>
Tensor Shape (2, 3)


Find a detailed reference to creating different tensors:


1.   [Converting python/numpy objects to tensors](https://www.tensorflow.org/api_docs/python/tf/convert_to_tensor)
2.   [Generating random values from a normal distribution](https://www.tensorflow.org/api_docs/python/tf/random/normal)
3.   [Converting tensor values to strings ](https://www.tensorflow.org/api_docs/python/tf/strings/as_string)
4.   [Createing a tensor of ones](https://www.tensorflow.org/api_docs/python/tf/ones)
5.   [Creating a tensor of zeroes](https://www.tensorflow.org/api_docs/python/tf/zeros)
6.   [TensorFlow for maths](https://www.tensorflow.org/api_docs/python/tf/math)





### [Variables](https://www.tensorflow.org/guide/variable) with tf.Variable()

A tensorflow Variable is a tensor that is used to store value that can later be updated. You need to initialize a variable with some value at the time of creation.

In [72]:
random_variable = tf.ones(shape=(3,3))
#random variable
tf_variable = tf.Variable(random_variable)
print(tf_variable)

#you can also update the values of your variable.
tf_variable.assign(tf.zeros(shape = (3,3)))
print(tf_variable)

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>


You can find more on updating a variable [here](https://www.tensorflow.org/api_docs/python/tf/Variable#assign_add).

Now we learn about the <b>[`GradientTape`](https://www.tensorflow.org/api_docs/python/tf/GradientTape)</b> which is used to record operations for automatic differentiation.

In [73]:
# computing derivative for the function 3x^2 at x = 3

x = tf.constant(3.0) #gradient at
with tf.GradientTape() as g:
  g.watch(x) #record the operations
  y = 3*x * x
dy_dx = g.gradient(y, x) 
print(dy_dx)


# you can also use nested GradientTape() for the second derivative
#computing second derivative for the function 4x^2 at x = 4.0

x = tf.constant(4.0)
with tf.GradientTape() as gt:
  gt.watch(x)
  with tf.GradientTape() as g:
    g.watch(x)  
    y = 4*x*x
  dy_dx = g.gradient(y, x)
d2y_dx2 = gt.gradient(dy_dx,x)
print(d2y_dx2)





tf.Tensor(18.0, shape=(), dtype=float32)
tf.Tensor(8.0, shape=(), dtype=float32)


## Practice Questions

#### 1. Create a constant tensor array 'x' like [2,3,4] and find element wise e^x.  Refer to the website [here](https://www.tensorflow.org/api_docs/python/tf/math/exp).



In [1]:
#your code here



#### 2. Declare a variable with a 3*2 shaped floating elements array with elements picked from a random normal distributions.   

In [2]:
#your code here


#### 3. Subtract 1 from every element of the above matrix.


In [3]:
#your code here


#### 4. Calculate the third derivative of the function 4x^3 + x^2 + 1 at x = 1

In [4]:
#your code here


#### 5. Calculate dot product of matrices [[1,2,3],[4,5,6],[7,8,9]] and [[1],[2],[3]] using tensorflow functions. Also, find the element wise multiplication of the two.

In [5]:
#your code here for dot product



In [6]:
# your code here for element wise product


#### <i>Happy Learning!</i>